#!/usr/bin/env php
<?php

declare(strict_types=1);

use GuzzleHttp\Client;
use GuzzleHttp\Exception\GuzzleException;
use Monolog\Handler\FilterHandler;
use Monolog\Handler\StreamHandler;
use Monolog\Level;
use Monolog\Logger;

require_once __DIR__ . '/vendor/autoload.php';

const LOG_CHANNEL = 'swarm-cron';
const DOCKER_STACK_NAME = 'swarm-cron';

$logger = new Logger(LOG_CHANNEL);
$stdoutHandler = new StreamHandler('php://stdout', Level::Debug);
$stderrHandler = new StreamHandler('php://stderr', Level::Error);
$logger->pushHandler(new FilterHandler($stdoutHandler, Level::Debug, Level::Warning));
$logger->pushHandler($stderrHandler);

$client = new Client(['base_uri' => 'http://localhost/v1.41/']);

array_shift($argv); // Remove the script name.

if (count($argv) === 0) {
    echo 'At least one argument is required.';
    // TODO print usage here.
    exit(1);
}

$subcommand = array_shift($argv);
if ($subcommand === 'crontab') {
    exit(crontab());
}
if ($subcommand === 'run') {
    $service = array_shift($argv);
    exit(run($service, $argv));
}
echo 'Invalid subcommand.';
// TODO print usage here.
exit(1);

function crontab(): int {
    global $logger;
    $crontabPath = '/etc/crontabs/swarm';
    $crontab = getenv('SWARM_CRON_CRONTAB');
    $crontabLines = array_map('trim', explode(PHP_EOL, $crontab));
    $logger->info(sprintf('Starting crontab generation to: %s', $crontabPath));

    $jobs = 0;
    file_put_contents($crontabPath, '');
    foreach ($crontabLines as $crontabLine) {
        if ($crontabLine === '') {
            continue;
        }
        if ($crontabLine[0] === '#') {
            continue;
        }
        $crontabLineChunks = preg_split('/\s+/', $crontabLine, 7);
        if (count($crontabLineChunks) < 7) {
            $logger->error(sprintf('Crontab line "%s" is not valid and will be skipped.', $crontabLine));
            continue;
        }
        $cronExpr = implode(' ', array_slice($crontabLineChunks, 0, 5));
        $service = escapeshellarg($crontabLineChunks[5]);
        $command = $crontabLineChunks[6];
        $swarmCrontabLine = sprintf('%s /srv/app/swarm-cron run %s %s', $cronExpr, $service, $command);
        file_put_contents($crontabPath, $swarmCrontabLine . PHP_EOL, FILE_APPEND);
        $logger->info(sprintf('Crontab line: %s', $swarmCrontabLine));
        $jobs++;
    }

    exec(sprintf('chmod 600 %s', escapeshellarg($crontabPath)));
    exec(sprintf('crontab %s', escapeshellarg($crontabPath)));

    $logger->info(sprintf('Crontab generated and activated with "%s" jobs!', $jobs));

    return 0;
}

function run(string $service, array $commandArray): int {
    global $logger, $client;
    $command = implode(' ', $commandArray);
    $logger->info(sprintf('Preparing cron service with command "%s" and service "%s"', $command, $service));

    try {
        $response = $client->request('GET', 'services/' . $service, [
            'query' => ['insertDefaults' => 1],
            'curl' => [
                CURLOPT_UNIX_SOCKET_PATH => '/var/run/docker.sock'
            ]
        ]);
    } catch (GuzzleException $e) {
        $logger->error(
            sprintf('Docker API error: %s - %s', $e->getMessage(), json_encode($e->getTrace(), JSON_THROW_ON_ERROR))
        );
        return 1;
    }

    $sourceServiceData = json_decode((string)$response->getBody(), false, 512, JSON_THROW_ON_ERROR);
    $cronServiceName = sprintf('swarm_cron_service_%s', md5($service . ':' . $command));
    $cronServiceSpec = $sourceServiceData->Spec;
    $cronServiceSpec->Name = $cronServiceName;
    $cronServiceSpec->TaskTemplate->ContainerSpec->Args = $commandArray;
    $cronServiceSpec->TaskTemplate->ContainerSpec->Healthcheck = (object) ['Test' => ['NONE']];
    $cronServiceSpec->TaskTemplate->RestartPolicy->Condition = 'none';
    $cronServiceSpec->Mode = (object) ['ReplicatedJob' => ['MaxConcurrent' => 1, 'TotalCompletions' => 1]];
    $cronServiceSpec->UpdateConfig = null;
    $cronServiceSpec->Labels->{'com.docker.stack.namespace'} = DOCKER_STACK_NAME;
    $cronServiceSpec->Labels->{'com.webgriffe.swarm-cron.service'} = $service;
    $cronServiceSpec->Labels->{'com.webgriffe.swarm-cron.command'} = $command;
    $logger->debug(sprintf('Prepared cron service spec: %s', json_encode($cronServiceSpec, JSON_THROW_ON_ERROR)));

    $cronServiceVersion = null;
    try {
        $response = $client->request('GET', 'services', [
            'query' => [
                'status' => 1,
                'filters' => json_encode(['name' => [$cronServiceName]], JSON_THROW_ON_ERROR)
            ],
            'curl' => [
                CURLOPT_UNIX_SOCKET_PATH => '/var/run/docker.sock'
            ]
        ]);
        $foundServicesData = json_decode((string)$response->getBody(), false, 512, JSON_THROW_ON_ERROR);
        if (count($foundServicesData) > 0) {
            $cronServiceData = $foundServicesData[0];
            if ($cronServiceData->ServiceStatus->RunningTasks > 0) {
                $logger->info(
                    sprintf(
                        'Cron service "%s" with command "%s" from service "%s" is still running and will not be ' .
                        're-started.',
                        $cronServiceName,
                        $command,
                        $service
                    )
                );
                return 0;
            }
            $cronServiceVersion = $cronServiceData->Version->Index;
        }
    } catch (GuzzleException $e) {
        $logger->error(
            sprintf('Docker API error: %s - %s', $e->getMessage(), json_encode($e->getTrace(), JSON_THROW_ON_ERROR))
        );
        return 1;
    }

    try {
        if ($cronServiceVersion !== null) {
            $client->request('DELETE', 'services/' . $cronServiceName, [
                'curl' => [
                    CURLOPT_UNIX_SOCKET_PATH => '/var/run/docker.sock'
                ]
            ]);
            $logger->info(
                sprintf(
                    'Deleted old, not-running, cron service "%s" with command "%s" from service "%s"',
                    $cronServiceName,
                    $command,
                    $service
                )
            );
        }
        $client->request('POST', 'services/create', [
            'json' => $cronServiceSpec,
            'curl' => [
                CURLOPT_UNIX_SOCKET_PATH => '/var/run/docker.sock'
            ]
        ]);
        $logger->info(
            sprintf(
                'Started cron service "%s" with command "%s" from service "%s"',
                $cronServiceName,
                $command,
                $service
            )
        );
    } catch (GuzzleException $e) {
        $logger->error(
            sprintf('Docker API error: %s - %s', $e->getMessage(), json_encode($e->getTrace(), JSON_THROW_ON_ERROR))
        );
        return 1;
    }

    return 0;
}
